# Generated by Django 3.2.6 on 2021-08-18 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_alter_product_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='quantity',
            field=models.PositiveIntegerField(null=True, verbose_name='Колличество'),
        ),
    ]
